# Generated by Django 5.1.1 on 2026-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_payment_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verification_source',
            field=models.CharField(blank=True, choices=[('callback', 'Client Callback'), ('webhook', 'Webhook'), ('system', 'System')], max_length=12),
        ),
    ]
